# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac7d923fbe0b2d213f33b298c911c8033cbb0dab2e99a7a69d35a83f96819dc13a46a62bbce5bf563e5fb9b7d9f5dd92ec3d7739bcdc2423bba53057191bd900

test:
  secret_key_base: 40ee8f8e2c7faae489c792997038aea0885356cce06b58c5bd9168cb5d852ff2d5a0db4f151acb905028502c51e8100d5d47b1f7eb1d3c00beac5e41e45b2a92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
